services:
  kutt:
    image: kutt/kutt:v2.7.4
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: kutt
      DB_PASSWORD: T1nyURLs!
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # TinyURL confifguration
      LINK_LENGTH: 6
      SITE_NAME: Tiny URLs
      DEFAULT_DOMAIN: 127.0.0.1:3000
      # Disable registration
      DISALLOW_REGISTRATION: "false"
      # Disable anonymous link creation
      DISALLOW_ANONYMOUS_LINKS: "true"
      # The daily limit for each user
      USER_LIMIT_PER_DAY: 100000
      # Create a cooldown for non-logged in users in minutes
      # Set 0 to disable
      NON_USER_COOLDOWN: 0
      # Max number of visits for each link to have detailed stats
      DEFAULT_MAX_STATS_PER_LINK: 5000
      # Use HTTPS for links with custom domain
      CUSTOM_DOMAIN_USE_HTTPS: "false"
      # A passphrase to encrypt JWT. Use a long and secure key.
      JWT_SECRET: ARWVT8BX73+XzwLiPMRWVQ==
      # Admin emails so they can access admin actions on settings page
      # Comma seperated
      ADMIN_EMAILS: info@ortussolutions.com
      # Invisible reCaptcha secret key
      # Create one in https://www.google.com/recaptcha/intro/
      # RECAPTCHA_SITE_KEY:
      # RECAPTCHA_SECRET_KEY:

      # Google Cloud API to prevent from users from submitting malware URLs.
      # Get it from https://developers.google.com/safe-browsing/v4/get-started
      # GOOGLE_SAFE_BROWSING_KEY:

      # Your email host details to use to send verification emails.
      # More info on http://nodemailer.com/
      # Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 25
      MAIL_SECURE: "false"
      MAIL_USER: foo
      MAIL_FROM: testy@testerson.com
      MAIL_PASSWORD: bar

      # The email address that will receive submitted reports.
      REPORT_EMAIL: info@ortussolutions.com

      # Support email to show on the app
      CONTACT_EMAIL: info@ortussolutions.com

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kutt
      POSTGRES_PASSWORD: T1nyURLs!
      POSTGRES_DB: kutt
      KUTT_API_KEY: ${KUTT_AUTHTOKEN}
    volumes:
      # - ./build/docker/postgres/initdb/setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: